apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-config
data:
  rsyslog.conf: |
    module(load="imudp")
    input(type="imudp" port="10515")
    *.* /var/log/syslog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-server
  template:
    metadata:
      labels:
        app: syslog-server
    spec:
      securityContext:
        fsGroup: 1000770000
        runAsUser: 1000770000
        runAsGroup: 1000770000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: rsyslog
        image: rsyslog/syslog_appliance_alpine
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 10515
          protocol: UDP
        volumeMounts:
        - name: rsyslog-config
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
        - name: varlog
          mountPath: /var/log
        - name: config-volume
          mountPath: /config
      volumes:
      - name: rsyslog-config
        configMap:
          name: rsyslog-config
      - name: varlog
        emptyDir: {}
      - name: config-volume
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-server
spec:
  selector:
    app: syslog-server
  ports:
    - protocol: UDP
      port: 10515
      targetPort: 10515
