apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-app
  template:
    metadata:
      labels:
        app: syslog-app
    spec:
      containers:
      - name: python-app
        image: syslog-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 514
          protocol: UDP
        env:
        - name: SYSLOG_HOST
          value: "127.0.0.1"
        - name: SYSLOG_PORT
          value: "514"
        volumeMounts:
        - name: rsyslog-socket
          mountPath: /var/run/rsyslog
      - name: rsyslog
        image: rsyslog/syslog_appliance_alpine:latest
        volumeMounts:
        - name: rsyslog-config
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
        - name: rsyslog-socket
          mountPath: /var/run/rsyslog
      volumes:
      - name: rsyslog-config
        configMap:
          name: rsyslog-config
      - name: rsyslog-socket
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rsyslog-config
data:
  rsyslog.conf: |
    # Load modules
    module(load="imuxsock")
    module(load="builtin:omfwd")

    # Listen on Unix socket
    input(type="imuxsock" Socket="/var/run/rsyslog/log.sock")

    # Forward to syslog server
    *.* action(type="omfwd"
              target="syslog-server"
              port="10515"
              protocol="udp"
              action.resumeRetryCount="5"
              queue.type="linkedList"
              queue.size="5")

    $DebugFile /var/log/rsyslog-debug.log
    $DebugLevel 2 
    