apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-app
  template:
    metadata:
      labels:
        app: syslog-app
    spec:
      containers:
      - name: python-app
        image: syslog-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 514
          protocol: UDP
        env:
        - name: SYSLOG_HOST
          value: "127.0.0.1"
        - name: SYSLOG_PORT
          value: "514"
      - name: fluentd
        image: fluentd-syslog:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <system>
      log_level debug
      suppress_repeated_stacktrace true
      emit_error_log_interval 10
      suppress_config_dump true
      root_dir /tmp/fluentd
    </system>

    <source>
      @type syslog
      port 514
      bind 0.0.0.0
      tag syslog
      <parse>
        @type regexp
        expression /^<(?<pri>\d+)>(?<message>.*)$/
        time_key time
        time_type string
        time_format %Y-%m-%dT%H:%M:%S%z
      </parse>
    </source>

    <match syslog.**>
      @type remote_syslog
      host syslog-server
      port 515
      protocol udp
      facility user
      severity info
      <buffer>
        flush_mode interval
        flush_interval 5
        flush_thread_interval 0.5
        flush_thread_burst_interval 0.5
      </buffer>
    </match> 
    